//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuestBook.API
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Post
    {
        public Nullable<int> UserId { get; set; }
        public int PostId { get; set; }

        [Required(ErrorMessage="Please provide a Post Title", AllowEmptyStrings = false)]
        public string PostTitle { get; set; }

        [Required(ErrorMessage = "Please provide Post Content", AllowEmptyStrings = false)]
        public string PostContent { get; set; }


        public System.DateTime PostDate { get; set; }
    
        public virtual User User { get; set; }

        public void Update(PostModel model)
        {
            //If new Post
            if(model.PostId == 0)
            {
                PostDate = DateTime.Now;
            }

            PostTitle = model.PostTitle;
            PostContent = model.PostContent;
            PostId = model.PostId;

        }
    }
}
