//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuestBook.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Nullable<int> UserId { get; set; }
        public int PostId { get; set; }
        public string PostTitle { get; set; }
        public string PostContent { get; set; }
        public System.DateTime PostDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
