//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuestBook.API
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Posts = new HashSet<Post>();
        }
    
        public int UserId { get; set; }

        [Required(ErrorMessage="Please provide a Username", AllowEmptyStrings=false)]
        public string Username { get; set; }

        [Required(ErrorMessage ="Please provide a paossword", AllowEmptyStrings =false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [StringLength(50,MinimumLength =7,ErrorMessage ="Password must be at least 7 characters long")]
        public string Password { get; set; }
        [Compare("Password", ErrorMessage ="Confirm password does not match")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string ConfirmPassword { get; set; }
        

        [Required(ErrorMessage ="Please provide an Email Address", AllowEmptyStrings =false)]
        public string EmailAddress { get; set; }
        [Required(ErrorMessage ="Please provide a phone number", AllowEmptyStrings =false)]
        public string PhoneNumber { get; set; }

        public System.DateTime CreatedDate { get; set; }
        public string TwitterHandle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }



        public void Update(UserModel model)
        {
            //If new User
            if(model.UserId == 0)
            {
                CreatedDate = DateTime.Now;
            }
            Username = model.Username;
            Password = model.Password;
            EmailAddress = model.EmailAddress;
            PhoneNumber = model.PhoneNumber;
            TwitterHandle = model.TwitterHandle;
            ConfirmPassword = model.ConfirmPassword;


        }
    }
}
